BlogBundle\Entity\Author:
    type: entity
    table: author
    repositoryClass: BlogBundle\Entity\AuthorRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        slug:
            type: string
        email:
            type: string

    oneToMany:
        posts:
            targetEntity: Post
            mappedBy: author
